<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Microsoft.eShopOnDapr.BuildingBlocks.Healthchecks</RootNamespace>
    <AssemblyName>Microsoft.eShopOnDapr.BuildingBlocks.Healthchecks</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dapr.Client" Version="1.15.2" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="8.0.14" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" Version="8.0.14" />
  </ItemGroup>

</Project>
