<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
	<RootNamespace>Microsoft.eShopOnDapr.Services.API.Abstraction</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapr.Client" Version="1.16.0" />
    <PackageReference Include="Dapr.Extensions.Configuration" Version="1.16.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.9" />
  </ItemGroup>

</Project>
